FROM ubuntu:22.04

ARG CACHEBUST=1
RUN echo "Cache bust: $CACHEBUST"

RUN apt-get update && apt-get install -y curl wget python3 python3-pip && pip install flask && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY app.py /app/

WORKDIR /app

CMD ["python3", "app.py"]
