FROM registry.access.redhat.com/ubi8/ubi-minimal

ARG APP_BUILD_NUMBER

ENV APP_BUILD=$APP_BUILD_NUMBER

CMD echo "Build number: $APP_BUILD"

#ENV APP_NAME="MyApp" APP_VERSION="1.0" APP_ENV="development"

#CMD echo "Running $APP_NAME v$APP_VERSION in $APP_ENV mode"
