version: '3.8'

services:
  redis:
    image: redis:alpine
#    ports:
#      - "6379:6379"

  webapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis


#    image: nginx:alpine
#    ports:
#      - "8080-8082:80"
#    depends_on:
#      - redis
#    deploy:
#      replicas: 3
